eureka:
  instance:
    hostname: localhost
  client:
    service-url.defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
eureka:
  instance:
    prefer-ip-address: true
